# Generated by Django 4.1.3 on 2022-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='adddetail',
            old_name='fooditem',
            new_name='add_item',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='fat',
            new_name='Protein',
        ),
        migrations.RemoveField(
            model_name='adddetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='item',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Carbohydrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='Fooditem',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
