# Generated by Django 4.1 on 2022-11-11 06:24

from django.db import migrations, models
import django.db.models.deletion
import food_items.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0004_totalenergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddate',
            name='date',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adddetail',
            name='date_d',
            field=models.ForeignKey(default=food_items.models.AddDate, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_items.adddate'),
        ),
    ]
