# Generated by Django 4.1 on 2022-11-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import food_items.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_items', '0005_alter_adddate_date_alter_adddetail_date_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adddetail',
            name='date_d',
            field=models.ForeignKey(default=food_items.models.AddDate, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_items.adddate'),
        ),
    ]
